spring:
  profiles.active: dev
  application.name: Rookie-Blog

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.lx.blog: DEBUG
    
springdoc:
  swagger-ui:
    path: /doc
